-- -- Enable the LSP Server
-- vim.lsp.enable({'clangd', 'lua-language-server', 'rust-analyzer' })
--
-- -- Setup an LspAttach autocommand to enable features based on client capabilities
-- vim.api.nvim_create_autocmd('LspAttach', {
--   callback = function(ev)
--     local client = vim.lsp.get_client_by_id(ev.data.client_id)
--     if client:supports_method('textDocument/completion') then
--       vim.lsp.completion.enable(true, client.id, ev.buf, { autotrigger = true })
--     end
--   end,
-- })
--
-- vim.cmd("set completeopt+=noselect")

-- vim.o.winborder = 'rounded'
--
-- vim.diagnostic.config({
--   -- Use the default configuration
--   -- virtual_lines = true
--
--   -- Alternatively, customize specific options
--   virtual_lines = {
--    -- Only show virtual line diagnostics for the current cursor line
--    current_line = true,
--   },
-- })
